name: wofscast
channels:
    - conda-forge
    - defaults
    - pytorch
    - nvidia
dependencies:
    - pip=24.0
    - cartopy=0.22.0
    - chex=0.1.85
    - netcdf4=1.6.5
    - optax=0.1.9
    - dask=2024.1.1
    - dm-haiku=0.0.11
    - dm-tree=0.1.8
    - jraph=0.0.6.dev0
    - matplotlib==3.8.2
    - numpy=1.24.4
    - pandas=2.2.0
    - rtree=1.2.0
    - scipy=1.12.0
    - trimesh=4.1.3
    - typing_extensions=4.9.0
    - xarray=2023.7.0
    - zarr=2.17.2
    - wandb
    - tqdm=4.66.2
    - pytorch-cuda=11.8
    - pip:
        - colabtools==0.0.1
        - jax[cuda]
        - torch==2.2.1
        - torchaudio==2.2.1
        - torchvision==0.17.1
    - python=3.10