# Notes: this environment works for the wofscast code, but 
# not quite for the diffusion add-on 

name: wofscast
channels:
    - conda-forge
    - pytorch
    - nvidia
dependencies:
    - pip=24.2
    - jax=0.4.24  # Specify the exact version of jax
    - jaxlib=0.4.24=*cuda*  # Ensure the specific version of jaxlib with CUDA support
    - cuda-nvcc
    - pytorch=2.2.1
    - pytorch-cuda=11.8
    - torchvision
    - torchaudio
    - accelerate=0.31.0
    - cartopy=0.22.0
    - chex=0.1.85
    - netcdf4=1.6.5
    - optax=0.1.9
    - dask=2024.1.1
    - dm-haiku=0.0.11
    - dm-tree=0.1.8
    - jraph=0.0.6.dev0
    - matplotlib==3.8.2
    - numpy=1.24.4
    - pandas=2.2.0
    - rtree=1.2.0
    - scipy=1.12.0
    - trimesh=4.1.3
    - typing_extensions=4.9.0
    - flax=0.8.5
    # Xarray 2024.1.1 raised TracerArrayConversionError, downgraded to 2023.7.0, the version 
    # used in colab in the demo notebook.
    - xarray=2023.7.0 
    - zarr=2.17.2
    - wandb
    - tqdm=4.66.2
    #- notebook=6.5.6
    - jupyter=1.0.0
    - diffusers=0.27.0
    - safetensors=0.4.3
    - pip:
        - colabtools==0.0.1
        # huggingface packages 
        #- transformers==4.40.0  
    - python=3.10
