# Configuration file to generate the 10-min timestep WoFSCast testing dataset
# with the original set of variables. Uses the legacy version of the 
# data generation, which will use the non-negative longitude, etc. 

#BASE_PATH = '/work2/wof/realtime/FCST/' 
BASE_PATH : '/work2/wofs_zarr'
OUT_PATH : '/work2/mflora/wofscast_datasets/dataset_10min_6hrs'
OUT_NORM_PATH : '/work2/mflora/wofscast_norm_stats/dataset_10min_6hrs'

# Timestep resolution for the dataset. 
timestep_minutes : 10  

# Number of timesteps to include in one sample. 
n_timesteps : 34      

# Time in minutes after forecast initialization to start sampling. 
offset : 0            

years : ['2021'] 

n_jobs : 20 

VARS_TO_KEEP : ['U', 
                'V', 
                'W', 
                'T', 
                'PH', 
                'PHB', 
                'QVAPOR', 
                'T2', 
                'RAINNC', 
                'COMPOSITE_REFL_10CM', 
                'UP_HELI_MAX',
                'HGT', 'XLAND'
                ]

#mems : [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
mems : [9]

init_times : ['1900', 
              #'1930', 
              '2000', 
              #'2030', 
              '2100', 
              #'2130', 
              '2200', 
              #'2230', 
              '2300', 
              #'2330',
              '0000', 
              #'0030',
              '0100', 
              #'0130',
              '0200', 
              #'0230',
              '0300']
